Wed Oct 23 11:29:39 CST 2024 : Apache Derby Network Server - 10.17.1.0 - (1913217) started and ready to accept connections on port 1527
----------------------------------------------------------------
Wed Oct 23 11:29:48 CST 2024:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.17.1.0 - (1913217): instance a816c00e-0192-ba6d-514d-0000075fc790 
on database directory /Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/bin/myNewDB with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@1cf4f579 
Loaded from file:/Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=21.0.4+8-LTS-274
user.dir=/Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/bin
os.name=Mac OS X
os.arch=aarch64
os.version=15.0.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
Wed Oct 23 14:46:25 CST 2024 Thread[#36,DRDAConnThread_7,5,main] (XID = 1108), (SESSIONID = 152), (DATABASE = myNewDB), (DRDAID = {77}), Cleanup action starting
java.sql.SQLInvalidAuthorizationSpecException: The user name '123' is not valid. 
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:96)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:230)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:431)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:360)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2400)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1399)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(EmbedConnection.java:1295)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:445)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
Caused by: ERROR 28502: The user name '123' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.initialize(GenericLanguageConnectionContext.java:384)
	at org.apache.derby.impl.db.BasicDatabase.setupConnection(BasicDatabase.java:311)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.startTransaction(TransactionResourceImpl.java:196)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1367)
	... 13 more
============= begin nested exception, level (1) ===========
ERROR 28502: The user name '123' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.initialize(GenericLanguageConnectionContext.java:384)
	at org.apache.derby.impl.db.BasicDatabase.setupConnection(BasicDatabase.java:311)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.startTransaction(TransactionResourceImpl.java:196)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1367)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(EmbedConnection.java:1295)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:445)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
============= end nested exception, level (1) ===========
Cleanup action completed
Wed Oct 23 14:46:25 CST 2024 Thread[#36,DRDAConnThread_7,5,main] (DATABASE = myNewDB), (DRDAID = {77}), The user name '123' is not valid. 
Wed Oct 23 14:46:35 CST 2024 Thread[#36,DRDAConnThread_7,5,main] (XID = 1109), (SESSIONID = 153), (DATABASE = myNewDB), (DRDAID = {78}), Cleanup action starting
java.sql.SQLInvalidAuthorizationSpecException: The user name '123' is not valid. 
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:96)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:230)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:431)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:360)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2400)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1399)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(EmbedConnection.java:1295)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:445)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
Caused by: ERROR 28502: The user name '123' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.initialize(GenericLanguageConnectionContext.java:384)
	at org.apache.derby.impl.db.BasicDatabase.setupConnection(BasicDatabase.java:311)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.startTransaction(TransactionResourceImpl.java:196)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1367)
	... 13 more
============= begin nested exception, level (1) ===========
ERROR 28502: The user name '123' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.initialize(GenericLanguageConnectionContext.java:384)
	at org.apache.derby.impl.db.BasicDatabase.setupConnection(BasicDatabase.java:311)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.startTransaction(TransactionResourceImpl.java:196)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1367)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(EmbedConnection.java:1295)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:445)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
============= end nested exception, level (1) ===========
Cleanup action completed
Wed Oct 23 14:46:35 CST 2024 Thread[#36,DRDAConnThread_7,5,main] (DATABASE = myNewDB), (DRDAID = {78}), The user name '123' is not valid. 
Wed Oct 23 14:46:36 CST 2024 Thread[#36,DRDAConnThread_7,5,main] (XID = 1110), (SESSIONID = 154), (DATABASE = myNewDB), (DRDAID = {79}), Cleanup action starting
java.sql.SQLInvalidAuthorizationSpecException: The user name '123' is not valid. 
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:96)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:230)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:431)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:360)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2400)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1399)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(EmbedConnection.java:1295)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:445)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
Caused by: ERROR 28502: The user name '123' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.initialize(GenericLanguageConnectionContext.java:384)
	at org.apache.derby.impl.db.BasicDatabase.setupConnection(BasicDatabase.java:311)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.startTransaction(TransactionResourceImpl.java:196)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1367)
	... 13 more
============= begin nested exception, level (1) ===========
ERROR 28502: The user name '123' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.initialize(GenericLanguageConnectionContext.java:384)
	at org.apache.derby.impl.db.BasicDatabase.setupConnection(BasicDatabase.java:311)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.startTransaction(TransactionResourceImpl.java:196)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1367)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(EmbedConnection.java:1295)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:445)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
============= end nested exception, level (1) ===========
Cleanup action completed
Wed Oct 23 14:46:36 CST 2024 Thread[#36,DRDAConnThread_7,5,main] (DATABASE = myNewDB), (DRDAID = {79}), The user name '123' is not valid. 
Wed Oct 23 14:46:39 CST 2024 Thread[#36,DRDAConnThread_7,5,main] (XID = 1111), (SESSIONID = 155), (DATABASE = myNewDB), (DRDAID = {80}), Cleanup action starting
java.sql.SQLInvalidAuthorizationSpecException: The user name '123' is not valid. 
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:96)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:230)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:431)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:360)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2400)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1399)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(EmbedConnection.java:1295)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:445)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
Caused by: ERROR 28502: The user name '123' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.initialize(GenericLanguageConnectionContext.java:384)
	at org.apache.derby.impl.db.BasicDatabase.setupConnection(BasicDatabase.java:311)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.startTransaction(TransactionResourceImpl.java:196)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1367)
	... 13 more
============= begin nested exception, level (1) ===========
ERROR 28502: The user name '123' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.initialize(GenericLanguageConnectionContext.java:384)
	at org.apache.derby.impl.db.BasicDatabase.setupConnection(BasicDatabase.java:311)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.startTransaction(TransactionResourceImpl.java:196)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1367)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(EmbedConnection.java:1295)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:445)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
============= end nested exception, level (1) ===========
Cleanup action completed
Wed Oct 23 14:46:39 CST 2024 Thread[#36,DRDAConnThread_7,5,main] (DATABASE = myNewDB), (DRDAID = {80}), The user name '123' is not valid. 
Wed Oct 23 14:46:48 CST 2024 Thread[#36,DRDAConnThread_7,5,main] (XID = 1112), (SESSIONID = 156), (DATABASE = myNewDB), (DRDAID = {81}), Cleanup action starting
java.sql.SQLInvalidAuthorizationSpecException: The user name '123' is not valid. 
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:96)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:230)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:431)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:360)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2400)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1399)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(EmbedConnection.java:1295)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:445)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
Caused by: ERROR 28502: The user name '123' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.initialize(GenericLanguageConnectionContext.java:384)
	at org.apache.derby.impl.db.BasicDatabase.setupConnection(BasicDatabase.java:311)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.startTransaction(TransactionResourceImpl.java:196)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1367)
	... 13 more
============= begin nested exception, level (1) ===========
ERROR 28502: The user name '123' is not valid. 
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:299)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:294)
	at org.apache.derby.iapi.util.IdUtil.getUserAuthorizationId(IdUtil.java:571)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.initialize(GenericLanguageConnectionContext.java:384)
	at org.apache.derby.impl.db.BasicDatabase.setupConnection(BasicDatabase.java:311)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.startTransaction(TransactionResourceImpl.java:196)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserIsNotARole(EmbedConnection.java:1367)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(EmbedConnection.java:1295)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:445)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:629)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:295)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:921)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1474)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1424)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3378)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1208)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1008)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:298)
============= end nested exception, level (1) ===========
Cleanup action completed
Wed Oct 23 14:46:48 CST 2024 Thread[#36,DRDAConnThread_7,5,main] (DATABASE = myNewDB), (DRDAID = {81}), The user name '123' is not valid. 
----------------------------------------------------------------
Wed Oct 23 16:04:42 CST 2024:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.17.1.0 - (1913217): instance 4b390189-0192-ba6d-514d-0000075fc790 
on database directory /Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/bin/myNewD with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@1cf4f579 
Loaded from file:/Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=21.0.4+8-LTS-274
user.dir=/Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/bin
os.name=Mac OS X
os.arch=aarch64
os.version=15.0.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Wed Oct 23 16:04:52 CST 2024:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.17.1.0 - (1913217): instance 7ab90278-0192-ba6d-514d-0000075fc790 
on database directory /Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/bin/myNew with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@1cf4f579 
Loaded from file:/Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=21.0.4+8-LTS-274
user.dir=/Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/bin
os.name=Mac OS X
os.arch=aarch64
os.version=15.0.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Wed Oct 23 16:09:42 CST 2024:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.17.1.0 - (1913217): instance 2a30c383-0192-ba6d-514d-0000075fc790 
on database directory /Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/bin/myNe with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@1cf4f579 
Loaded from file:/Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=21.0.4+8-LTS-274
user.dir=/Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/bin
os.name=Mac OS X
os.arch=aarch64
os.version=15.0.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Wed Oct 23 16:11:50 CST 2024:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.17.1.0 - (1913217): instance a1d3c47b-0192-ba6d-514d-0000075fc790 
on database directory /Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/bin/azalia with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@1cf4f579 
Loaded from file:/Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=21.0.4+8-LTS-274
user.dir=/Users/coleexz/Documents/GitHub/ApacheDerbyDBMS/db-derby-10.17.1.0-bin/bin
os.name=Mac OS X
os.arch=aarch64
os.version=15.0.1
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
